- lib/src/chat_theme.dart
- lib/src/widgets/chat.dart
When the background is light but message bubbles are dark, it's hard to find one text color that works both for received messages and for date dividers. Yet, the same `secondaryTextColor` theme property is used for both. So since the style of date dividers is defined by `subtitle2`, and to stick with the same logic as for `caption`/`captionColor`...
Added a subtitle2Color theme parameter so that the text color of date dividers can be independent from the text color of received message (`secondaryTextColor`). I set the default value of that setting to be the same as `secondaryTextColor` to keep some backward compatibility.
It might make sense to also add one for `subtitle1` but I didn't find any use of this and I wanted to minimize my changes.
> Make date divider color independent from received message text color

- doc/advanced-usage.md
- lib/src/widgets/chat.dart
- lib/src/widgets/message.dart
- lib/src/widgets/text_message.dart
The link preview is always on, which can be a security issue for encrypted chats, as the links will be always loaded.
I added the functionality so it can be disabled and added a sentence in the docs.
Also the regex for the link matching matches to bad urls, e.g.  ... or a... or ...x or ._.. etc. (Any use of ellipses or some morse-code will produce a url.) 
Maybe check: https://stackoverflow.com/questions/3809401/what-is-a-good-regular-expression-to-match-a-url
> Make preview url loading optional

- CHANGELOG.md
- lib/src/widgets/text_message.dart
- pubspec.yaml
This is ready to be merged
`Text` widget is now `SelectableText` for text messages
A user may want to copy a piece of information from the chat to use on another app, for example, a phone number.
`SelectableText` makes that process easier
Long press the text in a text messages
Unrelated issue
> Text is now selectable

- CHANGELOG.md
- lib/src/widgets/input.dart
- pubspec.yaml
This is ready to be merged. 
- Added a `FocusNode` to `_InputState` and its `TextField`. 
- Requesting focus on that node with a `GestureDetector` which wraps the entire composition input area (the part that has the border radius and contains the field itself, etc). 
- The majority of the changed lines are due to increased indentation from the widget wrapping; the only new lines inside `build(...)` are the new, outer `GestureDetector` (and its `onTap`), and `focusNode: _inputFocusNode,` inside the `TextField`.
- Tapping "off" still causes the field to lose focus. 
- This makes it easier for the user to bring up the keyboard, improving usability.
- Before this, if the user tapped a little high or low --but still reasonably "on the input area"-- the chat/app might appear
unresponsive.
- Tap …
> Made the full composition area trigger input focus (not just the inner field).

- CHANGELOG.md
- lib/src/widgets/chat.dart
- lib/src/widgets/input.dart
- pubspec.yaml
Adds a callback so we can know when the text changed
It is useful when we want, for example, show a typing indicator. In that case, we need a way to know when the user started typing.
Pass a `onTextChanged` callback to `Chat`
None
> On text changed callback

- example/lib/main.dart
Add SafeArea widget for attachment bottomsheet.
Without SafeArea, It broke layout.
- Run example.
- Touch attachment button.
**Before**
**After**
> Add SafeArea to bottomsheet on example 

- lib/src/chat_theme.dart
- lib/src/widgets/message.dart
Add parameter `sendingIcon` to `ChatTheme`.  
A more customizable `ChatTheme` makes the library flexible.
Pass the desired `Widget` as an argument to `sendingIcon` of `DefaultChatTheme`.
> Add support to set custom sendingIcon

- lib/flutter_chat_ui.dart
- lib/src/models/send_button_visibility_mode.dart
- lib/src/widgets/chat.dart
- lib/src/widgets/input.dart
- test/flutter_chat_ui_test.dart
- test/input.test.dart
It adds the ability to change the visibility of the `SendButton` by introducing a new enum property called `sendButtonVisibilityMode` to the `Chat` widget.
When `sendButtonVisibilityMode` parameter passed into the `Chat` widget, the `Input` widget will check if the parameter is set to `SendButtonVisibilityMode.always`. If it is, the `SendButton` always be visible regardless of the `TextField` state. 
If it is set to `SendButtonVisibilityMode.editing`, the `SendButton` will be visible only if the `TextField` is not empty.
The `sendButtonVisibilityMode` parameter defaults to `SendButtonVisibilityMode.editing` to maintain the existing behavior.
It will increase the flexibility when displaying the `SendButton`.
I've added some widget tests to not break the existing behavior and make sure …
> Allow setting the visibility of the SendButton

- lib/src/widgets/chat.dart
- lib/src/widgets/input.dart
It allows developers to specify an `onTap` function for the `TextField` inside the `Input` by adding `onTextFieldTap` parameter to the `Chat`.
I need it to be able to mark the received messages as `seen` when I tap on `TextField`. Most popular chat apps such as `Messenger`, `WhatsApp` also use this way.
None
> Add onTextFieldTap parameter

- lib/src/widgets/chat.dart
- lib/src/widgets/message.dart
There was no method to detect tap or long press on message status icon . This PR implements optional parameters to `Chat`: `onMessageStatusTap` and `onMessageStatusLongPress` to allow handling of these events.
It's a common case to click on status icon if message is not sent, in order to attempt sending it again.
Set `onMessageStatusTap` and `onMessageStatusLongPress` callbacks on `Chat` instance and click / longpress on one of status icons
> Added methods to detect status icon tap and long press

- lib/src/chat_l10n.dart
* add Traditional Chinese L10n
It adds support for Traditional Chinese (繁體中文-台灣).
It can helps Taiwan user to use this project.
Provide "const ChatL10nZhTW()" for property "l10n".
None.
> Add Traditional Chinese L10n

- example/lib/main.dart
- lib/src/widgets/chat.dart
- lib/src/widgets/message.dart
onMessageTap/1 onMessageLongPress/1 Add Parameter BuildContext context
onMessageTap/1 onMessageLongPress/1 两个函数，添加参数 BuildContext context
Easy to right-click menu location
便于右键菜单定位
> onMessageTap/1 onMessageLongPress/1 Add Parameter BuildContext context

- lib/src/widgets/chat.dart
- lib/src/widgets/message.dart
Some users are used to double-clicking a message to have the effect of a full-screen enlarged message; This method can be implemented
一些用户习惯了双击消息有一个全屏的放大消息的效果；该方法可以实现之
```
void _onMessageDoubleTap(BuildContext c1, types.Message message) async {
if (message is types.TextMessage) {
Get.bottomSheet(
GestureDetector(
onTap: () {
Get.back();
},
child: Container(
width: Get.width,
height: Get.height,
// Creates insets from offsets from the left, top, right, and bottom.
padding: EdgeInsets.fromLTRB(16, 24, 6, 10),
alignment: Alignment.center,
color: Colors.white,
child: Center(
child: Scrollbar(
child: SingleChildScrollView(
scrollDirection: Axis.vertical,
child: ExtendedText(
message.text,
textAlign: TextAlign.left,
style: TextStyle(
color: Colors.black,
fontSize: 20,
),
),
),
),
),
),
),
// …
```
> add onMessageDoubleTap/2 for message _bubbleBuilder onDoubleTap

- lib/src/chat_theme.dart
- lib/src/widgets/send_button.dart
Adds sendButtonMargin field to ChatTheme
I was unable to implement design in my project without it
Button was 'glued' to the right side
You can pass DefaultChatTheme(inputMargin: EdgeInsets.all(16)) to Chat()
There was no issue created for it
> Added sendButtonMargin to ChatTheme

- lib/src/chat_theme.dart
- lib/src/widgets/text_message.dart
Specifying a `sentMessageBodyLinkTextStyle` or `receivedMessageBodyLinkTextStyle` in the `ChatTheme` will, optionally, override the text style used for the link preview of text messages.
I faced an issue where I set a text style for body text in the chat theme but this style has a different decoration setting such that the underline also gets removed. Now, there is more flexibility.
> feat: allow overriding of link style

- example/lib/main.dart
- lib/src/widgets/chat.dart
- lib/src/widgets/message.dart
- pubspec.yaml
- test/text_message.test.dart
Added a callback for when messages become visible or scroll out of view.
This can be used to mark messages as seen when they were actually seen. The next step will be scrolling to the last unseen message.
Open the example app and look at the logger. I added a debug log message for when a message's visibility changes.
First part of #179 
Should I add this to the documentation or wait until I also create a PR for scroll to message?
> feat: add onMessageVisibilityChanged handler

- example/android/app/src/main/AndroidManifest.xml
- example/assets/messages.json
- example/ios/Runner/Info.plist
- lib/src/chat_theme.dart
- lib/src/widgets/text_message.dart
- pubspec.yaml
Add simple markdown rendering and replace link renderer with it too. Closes #157
Most modern chat apps have markdown support. Also, it is a bit cumbersome to maintain the header + text rendering logic here and in the link previewer package as well. Now, it is unified across both.
I added a simple Markdown example in the example app with link and email as well.
- Should there be an option to disable Markdown formatting in the `Chat` constructor?
> feat: add incomplete markdown support for text messages

- doc/advanced-usage.md
- lib/src/models/date_header.dart
- lib/src/util.dart
- lib/src/widgets/chat.dart
- test/util.test.dart
I've added `dateHeaderBuilder` to add ability to customize date header widget.
For customizing date header widget. For example I wanna add shadow, border or etc. to date header.
If you provide `dateHeaderBuilder` it should get called to build date header and return your custom widget. Else, default date header widget will be returned.
> Add dateHeaderBuilder

- lib/src/widgets/chat.dart
- lib/src/widgets/message.dart
- lib/src/widgets/text_message.dart
You can now specify options to enable the tap-to-open behavior from yesterdays PR.
No other way of configuring this yet.
[Let us know if this is related to any issue/pull request.](https://github.com/flyerhq/flutter_link_previewer/pull/39)
> Add options to open preview on title or image tap

- lib/src/models/send_button_visibility_mode.dart
- lib/src/widgets/input.dart
- test/input.test.dart
Added a new option of SendButtonVisibilityMode, the `hided`.
Enable the control of visibility, necessary in cases like lost connection of chat or other validations/conditions.
Just run the tests.
> A new SendButtonVisibilityMode

- lib/src/widgets/text_message.dart
It's a minor change, regarding the horizontal margin in text messages.
Text messages containing just 1 or more emoji's did not respect any horizontal margin set. It's always defaulted to `0.0`. Hence these kind of messages look different from all the other messages. 
Create a message with just one or more emoji characters.
It fixes issue #216.
> Respecting margin for emoji-only messages

- lib/src/chat_theme.dart
- lib/src/widgets/attachment_button.dart
- lib/src/widgets/input.dart
- lib/src/widgets/send_button.dart
Increase the tap target size of the send icon. For this, I had to apply the padding a bit differently and convert EdgeInsetsGeomtry to EdgeInset for this (which is anyways used most of the times).
Also, keep in mind that I extended the padding on the left of the send button by 12pt. Should we reduce the margin on the left side of the send button by that amount? It would be weird to not allow tapping to the left of the button.
Before, the send icon could only be tapped in a 24pt box. This can sometimes be rather fiddley and annoying, to some degree.
> feat: increase send button tap size

- lib/src/widgets/chat.dart
- lib/src/widgets/chat_list.dart
Scrollcontroller can now be passed to the Chat.
this would add the flexibility of controlling the chat scroll view outside the widget
To be able to control the scroll view. ex: a widget to scroll to the bottom of the chat.
I have a widget that is shown whenever a new message is received and the user is scrolled up in the chat, upon tapping the widget it scrolls to the end of the list.
Create a `scrollController` and pass it to the chat widget.
> feat: add scroll controller as a parameter

- lib/src/chat_theme.dart
- lib/src/widgets/attachment_button.dart
- lib/src/widgets/input.dart
Add option to theme that sets the margin for the attachment button analogously to how it is done for the send button.
More styling control
> Make attachment button margin configurable

- lib/src/widgets/chat.dart
- lib/src/widgets/message.dart
What does it do?
Adding avatar builder that can be future builder which can be used to fetch the latest user information to display in avatar.
Why is it needed?
Because the author currently comes from the message data, changes of profile picture only affect new messages (or all old messages would need to be replaced). It should be possible to optionally override Avatar information on the top level. 
How to test it?
add param avatarBuilder that accept Widget Function(String userId), with this we can access the user id for that message and use our own widget to fetch user avatar
Related issues/PRs
https://github.com/flyerhq/flutter_chat_ui/pull/207
This PR not includes user name builder, because i believe we can already override using existing builder.
> allow using custom avatar builder to always fetch newest profile

- lib/flutter_chat_ui.dart
- lib/src/util.dart
- lib/src/widgets/chat.dart
- lib/src/widgets/chat_user_avatar.dart
- lib/src/widgets/chat_user_name_header.dart
- lib/src/widgets/message.dart
- lib/src/widgets/text_message.dart
As described in #231, it is now possible to both override the name and avatar builder but also to reuse the current design with updated author data.
For one, we do not want to have to update the author fields for all messages when the profile picture changes.
Also, it should be possible to specify how the avatar is rendered. This allows us to add things like a loading spinner and such, or reuse already existing image caching logic.
Builds on top of #231, much of the credit goes to @dariuspo. Will make #207 irrelevant.
> Extract reusable widgets for name and avatar and add `avatarBuilder` and `nameBuilder`

- lib/src/widgets/text_message.dart
Emojis are now displayed using regular `(Selectable)Text` again.
The markdown merge seems to have broken the emojis-only messages.
> Fix emojis were not displayed anymore

- example/assets/messages.json
- lib/src/widgets/text_message.dart
Default to `https://` if no scheme in URL when trying to open it.
One regression with the switch from `linkify` to `flutter_parsed_text` was that loose URLs were still recognized but could not be opened just like that by `url_launcher`.
Run the example app and click on the `flyer.chat` link.
https://github.com/flyerhq/flutter_chat_ui/pull/260 also performed the migration to `canLaunchUrl`/`launchUrl`.
> Allow opening loose urls

- lib/src/widgets/chat.dart
- lib/src/widgets/message.dart
- lib/src/widgets/text_message.dart
Users can now specify how exactly links should open (e.g. use different launch mode or handle certain links inside their app). I also implemented a first draft options object for text messages which we could work off of.
Some apps have deep links that could be opened immediately without opening another browser.
> Add text message options to customize opening links

- lib/flutter_chat_ui.dart
- lib/src/widgets/chat.dart
- lib/src/widgets/image_gallery.dart
- Extracted image gallery widget to clean up code.
- Add scaling parameters and find better default min/max scales than infinity.
- Back button now just closes the gallery and not the whole example app (could be made configurable, what do you think?)
The image gallery always felt a bit weird to use to me. The features mentioned above are what I would expect from a regular chat app image gallery.
Just run the example app.
> Improve image gallery

- lib/src/widgets/input.dart
Fix for the input container changing size when typing something (compared to when the field is empty).
Before:
Now:
> Input text container changes size (when field is empty, compared to not empty)

- example/lib/main.dart
- lib/src/widgets/chat_list.dart
- lib/src/widgets/patched_sliver_animated_list.dart
Same as https://github.com/flyerhq/flutter_chat_ui/pull/296 but using `SliverAnimatedList`, including animated deletions. Fixes #287.
Adds the upstream patch https://github.com/flutter/flutter/pull/108710 to this code-base, and uses it in the `ChatList` to retain state the state of message widgets. Unblocks progress on this area until the upstream patch is merged and a new flutter version released.
> Message state persistence with animated list

- example/assets/messages.json
- lib/src/widgets/chat.dart
- lib/src/widgets/unseen_message_banner.dart
Keep track of scroll indices by message id to allow jumping to them.
I was not aware that the indices for `scroll_to_index` need to be ordered. Had to replace the hash code with a mapping.
Now you can use the latest message id as `lastSeenMessageID` and it should jump to it.
> Fix scroll to index

- lib/src/widgets/chat.dart
- lib/src/widgets/message/message.dart
- lib/src/widgets/message/text_message.dart
- Extract `TextMessageText`
- Also move isSelectable into TextOptions
- Makes the markdown capabilities more reusable e.g. for previews
> Extract text message text widget for previews

- lib/src/widgets/message/text_message.dart
It adds a parameter to `TextMessage` to allow specifying additional text matchers.
I need to display custom mentions in my text messages using widgets.
> Add ability to specify additional text matchers for text messages

- lib/src/widgets/chat_list.dart
Chat now only scrolls to the new message if it is really new (different ID) and not if it has changed in any way.
Until now, you are always sent to the beginning of the list if the first message in the chat has changed just a little. E.g. if the status of the message changes or if you slightly adjust other things afterwards (e.g. because you synchronize the message with the backend).
> fixes unnecessary scrolls to the bottom

- lib/src/widgets/chat.dart
- lib/src/widgets/chat_list.dart
I just added the ability to put a custom widget at the start of the `ChatList`.
This pull request is not breaking in any way, it just adds another parameter that has no effect on the behavior of the `Chat`.
You can only add custom widgets to the list so far by implementing a custom message for it and then using the `customMessageBuilder`, which is relatively complicated.
> adds bottomWidget to ChatList

- lib/src/widgets/chat.dart
Check if the unread header exists before trying to scroll to it. Previously settting `scrollOnOpen: true` when there were no unread messages led to a null check error.
Stop throwing errors.
> Fix scroll to unread when no unread messages exist

- lib/src/widgets/input/input.dart
added `autocorrect` and `enableSuggestions` props for `InputOptions`. By default, both values will be `true`.
Fixes https://github.com/flyerhq/flutter_chat_ui/issues/355
You can now use the `autocorrect` and `enableSuggestions` props for `InputOptions`
https://github.com/flyerhq/flutter_chat_ui/issues/355
> added `autocorrect` and `enableSuggestions` props

- lib/src/widgets/input/input.dart
Add an ability to control a text input field's keyboard type (multiline/number/email/etc.)
Sometimes developers need to pre-define an input keyboard type to a specific type. For example, a user should only type numbers in a quiz game. 
N/A
N/A
> Add "keyboardType" to the InputOptions

- lib/src/widgets/chat.dart
- lib/src/widgets/message/message.dart
- lib/src/widgets/message/text_message.dart
Instead of passing just user id to the `nameBuilder` let's pass whole `types.User` object. The id itself is rather useless, as we cannot get the real name of the user in such case.
I fully understand it's a breaking change though.
To enrich the `nameBuilder`. At the moment it's not possible to achieve as simple effect as:
```
nameBuilder: (w) => ExcludeSemantics(
child: chat_ui.UserName(author: w),
)
```
to render the name using default widget, but exclude it from the semantics tree.
> Make the nameBuilder use the User not string

- lib/src/widgets/chat_list.dart
#449 issue
This PR remove type indicator widget from tree when it is not show
We prevent render type_indicator widget when on don't use
You can open example screen, and open dev tools performance
[Let us know if this is related to any issue/pull request.](https://github.com/flyerhq/flutter_chat_ui/issues/449)
> Fixed repaint if type indicator don't use

- lib/src/chat_theme.dart
- lib/src/widgets/input/input.dart
Added two new theming variables to define an elevation and surface tint color for the input widget.
This allows to highlight the input text slightly, in line with the material ui guidlines.
> added theming options for text input

- lib/src/widgets/chat_list.dart
Prevent an exception 
`AnimationController methods should not be used after calling dispose.` 
While user pop out the chat while animation is in progress
> Add mounted check before animation

- lib/src/widgets/input/input.dart
Fix bug related on convertible character input issue like Japanese.
I think , some users who using CJK input are in trouble by this behavior.
1. Build  example project of flutter_chat_ui with web browser.
2. Enter Japanese characters by Roman alphabets. for example, こんにちは(ko nn ni ti ha)
3. If you entered above characters, you can see  "kおんにちは" (#476 )
4. Press enter key once, then "kおんにちは" is sent as message, and "おんにちは" remains in text field.( #514)
My commit fix these issues.
#514 
#476
> Japanese input bug

- lib/src/widgets/chat.dart
Add optional methods slidableMessageBuilder/2
Use it like this:
```
Chat(
user: logic.cuser,
messages: messages,
...
slidableMessageBuilder: (types.Message msg, Widget msgWidget) {
return GestureDetector(
onPanEnd: (DragEndDetails details) {
updateQuoteMessage(msg);
},
child: msgWidget,
);
},
...
```
_autoScrollIndexById modified to chatMessageAutoScrollIndexById, set to global variables, easy reference to reuse
_autoScrollIndexById 修改为 chatMessageAutoScrollIndexById，设置为全局变量，便于引用方复用
```
return GestureDetector(
onTap: () {
debugPrint("> on quoteMsg_onTap");
ChatLogic loigc = Get.find();
int msgIdIndex = chatMessageAutoScrollIndexById[quoteMsg.id] ?? 0;
if (msgIdIndex > 0) {
loigc.state.scrollController.scrollToIndex(
msgIdIndex,
duration: const Duration(milliseconds: 250),
);
} else {
// …
```
> add slidableMessageBuilder/2 optional method

- lib/flutter_chat_ui.dart
- lib/src/models/matchers.dart
- lib/src/widgets/message/system_message.dart
- lib/src/widgets/message/text_message.dart
Extracts the text matchers to a separate file.
To make them reusable outside of the library, e.g. displaying message previews in a chat list and still get the matching.
> Make text matchers reusable

- lib/src/widgets/input/send_button.dart
Add a [Semantics](https://api.flutter.dev/flutter/widgets/Semantics-class.html) around a SendButton.
It is different from a "tooltip", Tooltip ads a visual help on the long press, but this adds additional metadata to a Widget.
Better support for accessibility
But personally, I need it because of [maestro](https://maestro.mobile.dev/platform-support/flutter). It will allow for the button to be located.
No change in behaviour.
From UIAutomatorViewer (android only)
Before:
After: 
Notice the `content-desc` property.
No existing issue
> Add Semantics to Send Button

- lib/src/chat_theme.dart
- lib/src/widgets/chat.dart
add a messageMinWidth option in the chat theme configure
if we run the App in macOS, the max message width is still 440.  looks very unusual.
set messageMinWidth of the chat theme to [double. infinity] and run it on macOS.
https://github.com/flyerhq/flutter_chat_ui/issues/450
> #450 update: add message min width

- README.md
Hi, Thank you for your awesome project! I have a some correction for links in README.  
In [pub.dev docs](https://pub.dev/documentation/flutter_chat_ui/latest/), some relative path links are not working.
So, I've fixed them by changing absolute path links.
Thanks! ☺️
For documentation usability.
> Fix README link to absolute path for pub.dev

- lib/src/chat_l10n.dart
Added i10n class for Persian language. The standard locale for Persian is `fa` and `fa-IR` is the most used one.
> Adds l10n for Persian language (fa locale).

- lib/src/chat_theme.dart
- lib/src/widgets/message/message.dart
This change adds support for overriding the bubbleMargin property using ChatTheme. 
This allows users of the package to customize the margin of the chat bubbles, enabling scenarios where the user wants the message to take the entire width of the screen.
> Add support for overriding bubbleMargin using ChatTheme

- lib/src/conditional/io_conditional.dart
- lib/src/widgets/message/user_avatar.dart
This pull request adds support for AssetImage in the IOConditional class. This allows the package to correctly handle image assets from the Flutter assets directory.
Currently, the package doesn't handle asset URIs correctly, causing errors when trying to display images from the assets folder.
Modified the `getProvider` method in `IOConditional` to check for URIs starting with 'assets/' and use `AssetImage` for those cases.
This change allows users to easily display images from their assets folder without encountering errors, improving the package's flexibility and ease of use.
Tested with local asset images in a sample Flutter project. The images now display correctly in the chat UI.
Please review and let me know if any changes are needed.
> Add support for AssetImage in IOConditional

- lib/src/util.dart
- lib/src/widgets/chat.dart
Allows developers to arbitrarily set the spacing between message groups
Previously, the value was fixed at 12, making it impossible to set the value arbitrarily
You can test this by simply setting the value in Chat as shown below
```dart
body: Chat(
messagesSpacerHeight: 3,
~~~~~
)
```
None
> Update to set a custom value for the gap between message groups

- lib/src/chat_theme.dart
- lib/src/widgets/chat_list.dart
What does it do?
This PR adds a new parameter, chatContentPadding, which allows developers to customize the padding inside the chat content area. This provides more flexibility in controlling the spacing around the chat content within the chat container.
Why is it needed?
The current version of flutter_chat_ui does not offer a way to adjust the padding inside the chat content area. By adding this feature, developers can better match the chat UI to their specific design requirements, ensuring that the chat content aligns properly within different layouts.
How to test it?
To test the new chatContentPadding parameter:
Integrate the updated library into an existing Flutter project.
Use the chatContentPadding parameter in the Chat widget to set custom padding values.
Verify that the padding is …
> Add customization options for padding in chat area

- packages/flutter_chat_core/pubspec.yaml
As of right now the latest flutter version has `flutter_localizations` with [intl pinned](https://github.com/flutter/flutter/blob/c23637390482d4cf9598c3ce3f2be31aa7332daf/packages/flutter_localizations/pubspec.yaml#L14) at `0.19.0`. This meas that apps that use `flutter_localizations` are unable to import `flutter_chat_core`.
> Downgrade intl version

- examples/flyer_chat/lib/api/api.dart
- examples/flyer_chat/lib/basic.dart
- examples/flyer_chat/lib/create_message.dart
- examples/flyer_chat/lib/gemini.dart
- examples/flyer_chat/lib/local.dart
- packages/flutter_chat_core/lib/src/models/message.dart
- packages/flutter_chat_core/lib/src/models/message.freezed.dart
- packages/flutter_chat_core/lib/src/models/message.g.dart
- packages/flutter_chat_core/lib/src/models/user.dart
- packages/flutter_chat_core/lib/src/models/user.freezed.dart
- packages/flutter_chat_core/lib/src/models/user.g.dart
- packages/flutter_chat_core/test/chat_controller/in_memory_chat_controller_test.dart
- packages/flutter_chat_core/test/models/message_test.dart
- packages/flutter_chat_ui/lib/src/avatar.dart
- packages/flutter_chat_ui/lib/src/chat_message/chat_message_internal.dart
- packages/flutter_chat_ui/lib/src/simple_text_message.dart
- packages/flyer_chat_file_message/lib/src/flyer_chat_file_message.dart
- packages/flyer_chat_image_message/lib/src/flyer_chat_image_message.dart
- packages/flyer_chat_text_message/lib/src/flyer_chat_text_message.dart
- `createdAt` no longer required in the `Message` model
- `sending` is removed from the `Message` model - add `sending: true` to the `metadata` of the `Message` model for the same behaviour 
- `isOnlyEmoji` is removed from the text message model - add `isOnlyEmoji: true` to the `metadata` of the text message for the same behaviour
- `firstName` and `lastName` is replaced with `name` for the `User` model
- message widgets - hide status for the received messages
> feat: various changes

- examples/flyer_chat/lib/hive_chat_controller.dart
- examples/flyer_chat/lib/sembast_chat_controller.dart
- packages/flutter_chat_core/lib/src/chat_controller/chat_operation.dart
- packages/flutter_chat_core/lib/src/chat_controller/in_memory_chat_controller.dart
- packages/flutter_chat_ui/lib/src/chat_animated_list/chat_animated_list.dart
Hello 
@demchenkoalex 
Sorry this PR complements #756 and sadly requires an API change.
Currently the list does not listen to `ChatOperation.update`. When such an operation happens, all `ChatMessages` listen to it and eventually react updating themselves.
This means if the widget is in memory it will properly update **but** 
- if it is discarded
- then rebuilt
it will use the value at it's index in `_oldList` and this value has not been updated so the value prior to the update will be displayed.
I modified the signature to pass the `index` because usually if a client performs an update he must have calcultated it, like in all your examples.
If we want retrocompatibility we could make it optional and search for the message of correct id in the _oldList but this seemed less efficient.
- I …
> Fix update operation not persisted in the list

- packages/flyer_chat_image_message/lib/src/flyer_chat_image_message.dart
V1 allowed a custom `ImageProvider` to be defined with `imageProviderBuilder`.
This is a feature I need because I use the same cacheManager to display the chat's images (using [`CachedNetworkImage`](https://pub.dev/packages/cached_network_image) ( not the one from `crosscache`) in other part of the app.
Not sure I could do this with crossCache + it would mean losing cache on migration
> Allow custom ImageProvider

- packages/flyer_chat_text_message/lib/src/flyer_chat_text_message.dart
Currently when rendering the TextMessage with GptMarkdown, link are formatted well but won't be functional. Goal of this Pull request is to allow to send callback function to GptMarkdown, in order to make the link usable.
> fix: add tap callback function for the GptMarkdown link

- packages/flutter_chat_core/lib/src/models/builders.dart
- packages/flutter_chat_core/lib/src/models/builders.freezed.dart
- packages/flutter_chat_ui/lib/flutter_chat_ui.dart
- packages/flutter_chat_ui/lib/src/chat_animated_list/chat_animated_list.dart
- packages/flutter_chat_ui/lib/src/empty_chat_list.dart
Tentative to allow displaying a widget while the `chatList`  is empty as requested in #763 .
I defaulted to a centered text (same as v1)
I saw several options
- Replace the `sliverList` in `buildSlivers` : that seemed like the perfect one, as it allowed any Widget even another Sliver. But this caused a lot of issue since `_listKey.currentState` could not be defined on insert. It felt a bit too risky
- Add it as single element of the `SliverList` => hard to manage position, no sliver
- As an overlay in the Stack: current implementation. Looks quite ok except the centering does not take the `Composer` height into account
PS: build on top of #756 so to merge afterwards
> Add an empty list widget and builder

- examples/flyer_chat/lib/api/api.dart
- examples/flyer_chat/lib/gemini.dart
- examples/flyer_chat/lib/local.dart
- packages/flutter_chat_core/lib/src/models/builders.dart
- packages/flutter_chat_ui/lib/src/chat_message/chat_message_internal.dart
Exposing those 2 attributes in the builders, allow for more customization
For example only showing Time/status for the last message of the group
```dart
textMessageBuilder: (
context,
message,
index, {
required bool isSentByMe,
MessageGroupStatus? groupStatus,
}) =>
FlyerChatTextMessage(
message: message,
index: index,
showStatus: _shouldDisplayStatus(groupStatus),
showTime: _shouldDisplayTime(groupStatus),
),
```
Note: I choose not to remove the `isSentByMe` logic inside the UI package (what would require user to pass it manually in each builder)
> Expose isSentByMe and groupStatus in all messages builders

- packages/flutter_chat_ui/lib/src/chat_message/chat_message.dart
- packages/flutter_chat_ui/lib/src/utils/typedefs.dart
add method OnMessageDoubleTapCallback;
add param BuildContext context for OnMessageTapCallback and OnMessageLongPressCallback
The following functions must be in the context of the message widget
```
// 消息长按事件
void _onMessageLongPress(
BuildContext c1,
Message message, {
int? index,
LongPressStartDetails? details,
}) {
iPrint('_onMessageLongPress');
// BuildContext c1 = getx.Get.context!;
final menu = popupmenu.PopupMenu(
context: c1,
items: logic.getPopupMenuItems(message),
onClickMenu: onClickMenu,
);
final renderBox = c1.findRenderObject() as RenderBox;
final offset = renderBox.localToGlobal(Offset.zero);
double l = offset.dx / 2 - renderBox.size.width / 2 + 75.0;
double r = renderBox.size.width / 2 - 75.0;
double dx = message.authorId == UserRepoLocal.to.currentUid ? r : l;
double dy = …
```
> add method OnMessageDoubleTapCallback; add param BuildContext context for OnMessageTapCallback and OnMessageLongPressCallback

- packages/flyer_chat_text_message/lib/src/flyer_chat_text_message.dart
Allow to customize the links colors rendered by GptMarkdown.
Note that there is currently a bug in GptMarkdown where it's ignored  https://github.com/Infinitix-LLC/gpt_markdown/pull/74
> Allow set linksColor
