- CHANGELOG.md
- lib/src/models/date_header.dart
- lib/src/util.dart
- lib/src/widgets/chat.dart
- lib/src/widgets/chat_list.dart
- pubspec.yaml
- I've created an optional property called `customDateFormat` that allows the user to have custom dates
- I've also done a very small code optimization where an error in `ChatList` will return `const SizedBox` instead of `Container`
We would have more flexibility when showing dates
`Chat` now has a property called `customDateFormat`. To test, pass a `DateFormat` to it
None
> Adds the possibility to customize the date format

- lib/src/chat_l10n.dart
Add locale for Korean
It helps korean users.
> Add locale Korean

- lib/src/widgets/input.dart
- lib/src/widgets/message.dart
- pubspec.yaml
Describe the technical changes you did.
> Some fixes

- lib/src/chat_l10n.dart
It adds support for the Turkish language.
It helps Turkish users.
> Add Turkish l10n

- lib/src/widgets/chat.dart
Adds possibility to replace default Input with custom Widget
https://github.com/flyerhq/flutter_chat_ui/issues/45
https://github.com/flyerhq/flutter_chat_ui/issues/45
> Add custom bottom widget

- lib/src/widgets/chat.dart
- lib/src/widgets/message.dart
Describe the technical changes you did.
> Added a custom text builder

- lib/src/chat_theme.dart
Fix for https://github.com/flyerhq/flutter_chat_ui/issues/197
The dark chat theme was broken on the latest version
Create a chat with the theme set to DarkChatTheme()
https://github.com/flyerhq/flutter_chat_ui/issues/197
> Dark Chat Theme Broken On Latest Version

- lib/src/chat_l10n.dart
Allow users to show German translations
Translations are always useful ;)
Specify `ChatL10nDe` as `l10n` argument of `Chat` widget.
N/A
> localize: add German translations

- lib/src/models/send_button_visibility_mode.dart
- lib/src/widgets/input.dart
- test/input.test.dart
Renamed enum value `hided` to `hidden` 
Proper English
> Rename send button invisibility mode enum from hided to hidden

- lib/flutter_chat_ui.dart
Make sure people can actually set these options from the outside.
> Add missing export for `PreviewTapOptions`

- lib/src/widgets/input.dart
- lib/src/widgets/input_text_field_controller.dart
- lib/src/widgets/pattern_style.dart
- lib/src/widgets/text_message.dart
Format text input message with pattern style.
Text message already using pattern style to format text messages, like. bold, italic, etc.
Not related to any issues/PRs
> Add bold, italic, strikethrough & code style to input

- lib/src/conditional/browser_conditional.dart
- lib/src/conditional/conditional.dart
- lib/src/conditional/io_conditional.dart
- lib/src/widgets/chat.dart
- lib/src/widgets/image_gallery.dart
- lib/src/widgets/message/image_message.dart
- lib/src/widgets/message/message.dart
- lib/src/widgets/message/user_avatar.dart
https://github.com/flyerhq/flutter_chat_ui/issues/326
> provide option to pass headers to networkimage

- lib/src/util.dart
- lib/src/widgets/chat.dart
https://github.com/flyerhq/flutter_chat_ui/issues/334
> pass new parameter for utc support

- example/pubspec.yaml
Make example app build successfully
Fix errors when building example app
```
cd example
flutter run
```
No
> Fix issue when building example

- example/ios/Podfile.lock
- example/ios/Runner.xcodeproj/project.pbxproj
- example/pubspec.yaml
- pubspec.yaml
Upgrade packages
To have support on the latest visibility_detector version.
> Upgrade packages

- lib/src/chat_l10n.dart
It added Swedish translations
Support for more languages
--
--
> added swedish localizations

- lib/src/chat_l10n.dart
Added Finnish localization
More translation options
//
Ready to be merged
> added Finnish l10n

- CHANGELOG.md
- lib/src/widgets/chat.dart
- lib/src/widgets/message/message.dart
Describe the technical changes you did.
> fix image provider builder

- lib/src/widgets/chat_list.dart
Correctly formatted the code.
CI is no longer failing because of code that is not correctly formatted.
> Fix formatting

- lib/src/widgets/chat.dart
- lib/src/widgets/message/message.dart
PR Discussion #286
Ready to be merged
For ease of applying custom avatar builder to chat.
Describe the technical changes you did.
> AvatarBuilder to be of type Function(User)

- doc/advanced-usage.md
Decided to add documentation for newly introduced highlight on scroll functionality (it was not obvious for me co configure that).
> Updating documentation

- lib/src/widgets/chat.dart
Added paramter for control message width.
> Add message width ratio

- lib/flutter_chat_ui.dart
- lib/src/widgets/chat_list.dart
- lib/src/widgets/typing_indicator.dart
Typing widget builder for custom Typing
> Typing widget builder

- lib/src/widgets/chat.dart
Message A is a reply message to message B. At this time, message A contains a button that can be clicked to scroll to message B. At this time, I need B to appear at the top.
> Added optional scroll preferPosition to scrollController.scrollToIndex

- examples/flyer_chat/lib/api/api.dart
- examples/flyer_chat/lib/gemini.dart
- examples/flyer_chat/lib/local.dart
- examples/flyer_chat/lib/widgets/input_action_bar.dart
- packages/flutter_chat_ui/lib/src/chat_animated_list/chat_animated_list.dart
- packages/flutter_chat_ui/lib/src/chat_animated_list/chat_animated_list_reversed.dart
- packages/flutter_chat_ui/lib/src/chat_input.dart
- packages/flutter_chat_ui/lib/src/scroll_to_bottom.dart
- packages/flutter_chat_ui/lib/src/utils/keyboard_mixin.dart
- handle safe area automatically (optional, on by default)
- scroll content up with the keyboard when opened
- support action bar on top of the input (with example)
https://github.com/user-attachments/assets/da6e481f-a1c9-4162-af8b-d2f70f5e62d9
> feat: handle safe area, scroll content with the keyboard

- examples/flyer_chat/lib/api/api.dart
- examples/flyer_chat/lib/gemini.dart
- examples/flyer_chat/lib/local.dart
- packages/flutter_chat_core/lib/src/models/builders.dart
- packages/flutter_chat_core/lib/src/theme/image_message_theme.dart
- packages/flutter_chat_core/lib/src/theme/input_theme.dart
- packages/flutter_chat_core/lib/src/utils/typedefs.dart
- packages/flutter_chat_ui/lib/src/chat.dart
- packages/flutter_chat_ui/lib/src/chat_animated_list/chat_animated_list.dart
- packages/flutter_chat_ui/lib/src/chat_animated_list/chat_animated_list_reversed.dart
- packages/flutter_chat_ui/lib/src/chat_message/chat_message.dart
- packages/flutter_chat_ui/lib/src/chat_message/chat_message_internal.dart
- packages/flutter_chat_ui/lib/src/simple_text_message.dart
- packages/flyer_chat_image_message/lib/src/flyer_chat_image_message.dart
- packages/flyer_chat_text_message/lib/src/flyer_chat_text_message.dart
> feat: message grouping

- .cursor/rules/streaming-text-message.mdc
- examples/flyer_chat/lib/gemini.dart
- examples/flyer_chat/lib/gemini_stream_manager.dart
- examples/flyer_chat/pubspec.yaml
- packages/flutter_chat_core/CHANGELOG.md
- packages/flutter_chat_core/lib/src/models/builders.dart
- packages/flutter_chat_core/lib/src/models/builders.freezed.dart
- packages/flutter_chat_core/lib/src/models/message.dart
- packages/flutter_chat_core/lib/src/models/message.freezed.dart
- packages/flutter_chat_core/lib/src/models/message.g.dart
- packages/flutter_chat_ui/CHANGELOG.md
- packages/flutter_chat_ui/lib/src/chat_message/chat_message_internal.dart
- packages/flutter_chat_ui/lib/src/simple_text_message.dart
- packages/flyer_chat_file_message/lib/src/flyer_chat_file_message.dart
- packages/flyer_chat_text_message/lib/src/flyer_chat_text_message.dart
- packages/flyer_chat_text_stream_message/CHANGELOG.md
- packages/flyer_chat_text_stream_message/LICENSE
- packages/flyer_chat_text_stream_message/README.md
- packages/flyer_chat_text_stream_message/analysis_options.yaml
- packages/flyer_chat_text_stream_message/lib/flyer_chat_text_stream_message.dart
- packages/flyer_chat_text_stream_message/lib/src/flyer_chat_text_stream_message.dart
- packages/flyer_chat_text_stream_message/lib/src/stream_state.dart
- packages/flyer_chat_text_stream_message/lib/src/text_segment.dart
- packages/flyer_chat_text_stream_message/pubspec.yaml
> text stream support

- packages/flutter_chat_ui/lib/src/chat_animated_list/chat_animated_list.dart
Fixes #769 
Maybe this should not be in pixels but % (0-1) of the list
> fix: scroll to bottom button appearance threshold #769

- examples/flyer_chat/lib/hive_chat_controller.dart
- examples/flyer_chat/lib/main.dart
- examples/flyer_chat/lib/pagination_mock_database.dart
- examples/flyer_chat/lib/pagination_newer.dart
- examples/flyer_chat/lib/pagination_older.dart
- packages/flutter_chat_core/lib/src/chat_controller/chat_operation.dart
- packages/flutter_chat_core/lib/src/chat_controller/in_memory_chat_controller.dart
- packages/flutter_chat_ui/lib/src/chat_animated_list/chat_animated_list.dart
- packages/flutter_chat_ui/lib/src/chat_animated_list/chat_animated_list_reversed.dart
- packages/flutter_chat_ui/lib/src/load_more.dart
- packages/flutter_chat_ui/lib/src/utils/load_more_notifier.dart
https://github.com/flyerhq/flutter_chat_ui/issues/824
> feat: implement two-sided pagination
